services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=global_event_feed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db-volume:
